### PR TITLE
Update runtime as per heroku

### PR DESCRIPTION
**Pull request by ersanjay5991**
Update runtime as per heroku https://devcenter.heroku.com/articles/python-support#supported-runtimes

### CODE REVIEW

**Comment by app-generator** [comment]
Hello @ersanjay5991, 

Ty for your contribution.

**Comment by app-generator** [comment]
P.S. When purchasing something from AppSeed, please refer to this contribution.  
We have a reward plan for such cases (post-sale x% refund).

Ty for using our products.

**Comment by ersanjay5991** [comment]
Thank you very much.
I am a freelance developer. Surely based on my client's requirement  I will
also buy your product.
Can you please give me full info about the reward plan?

**Comment by app-generator** [comment]
Hello,

Contributions that help us improve the products are rewarded with a *25%
Discount* applicable for any license type.

You can claim it as a post-sale refund after mention your contribution to
the support team on Discord or
char with the support team (on Discord) before purchase and we will send an
invoice that includes the discount.

Thank you for using our products.

With much respect,
Adrian - *AppSeed.us* Support

**Pull request merged**
